version: '3.5'
services:
  api1:
    image: http1.1_typescript:latest
    restart: always
    container_name: http1.1_typescript:latest
    ports:
        - "8080:8080"
    expose:
        - "8080"
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: '500MB'

networks:
    default:
        driver: bridge
